{
 "title": "Analytics NGINX | Staging",
 "tags": [ "metrics" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(cadvisor_build_info{env=~\"$env\"},instance)"
    }
   },
   {
    "name": "filename",
    "label": "filename",
    "query": {}
   },
   { "name": "job", "label": "job", "query": "integrations/nginx-file" },
   { "name": "env", "label": "env", "query": "staging|general" }
  ]
 },
 "panels": [
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (status) (count_over_time({filename=~\"$filename\", instance=\"$instance\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(instance) (count_over_time({filename=~\"$filename\", instance=\"$instance\"}[$__interval]))  "
    }
   ]
  },
  {
   "title": "% of 500 requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "(sum by(instance) (count_over_time({filename=~\"$filename\", instance=\"$instance\"} | json | __error__=`` | status = `500` [$__interval])) * 100) / sum by(instance) (count_over_time({filename=~\"$filename\", instance=\"$instance\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "(sum by(instance) (count_over_time({filename=~\"$filename\", instance=\"$instance\"} | json | __error__=`` | status =~ `5.*` | status != `500` [$__interval])) * 100) / sum by(instance) (count_over_time({filename=~\"$filename\", instance=\"$instance\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (sum_over_time({filename=~\"$filename\", instance=\"$instance\"} | json | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  { "title": "Recent Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=~\"$filename\", instance=\"$instance\"} | json | line_format `Hostname {{.server_name}} request for {{.request_uri}} with HTTP status: {{.status}} from {{.remote_addr}} located {{.geoip_country_code}}`"
    }
   ]
  },
  {
   "title": "Sources & Behaviours",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top IPs",
     "type": "table",
     "gridPos": { "h": 27, "w": 9, "x": 0, "y": 28 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(5, sum by(remote_addr) (count_over_time({filename=~\"$filename\", instance=\"$instance\"} | json | __error__=`` [$__interval])))",
       "legendFormat": "{{remote_addr}}"
      }
     ]
    },
    {
     "title": "Top HTTP Referers - Exclude Panxora Site",
     "type": "table",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 28 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(10, sum by(http_referer) (count_over_time({filename=~\"$filename\", instance=\"$instance\"} | json | __error__=`` [$__interval])))",
       "legendFormat": "{{http_referer}}"
      }
     ]
    },
    {
     "title": "Top Requested Pages - Excluding '/'",
     "type": "table",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 34 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(10, sum by(request_uri) (count_over_time({filename=~\"$filename\", instance=\"$instance\"} | json | __error__=`` [$__interval])))",
       "legendFormat": "{{request_uri}}"
      }
     ]
    },
    {
     "title": "Top HTTP Referers",
     "type": "table",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 42 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(5, sum by(http_referer) (count_over_time({filename=~\"$filename\", instance=\"$instance\"} | json | __error__=`` [$__interval])))",
       "legendFormat": "{{http_referer}}"
      }
     ]
    },
    {
     "title": "Top User Agents",
     "type": "table",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 48 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(10, sum by(http_user_agent) (count_over_time({filename=~\"$filename\", instance=\"$instance\"} | json | __error__=`` [$__interval])))",
       "legendFormat": "{{http_user_agent}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Statistics Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "95th percentile of Request Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "quantile_over_time(0.95,{filename=~\"$filename\", instance=\"$instance\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]) by (instance)",
       "legendFormat": "95th percentile"
      },
      {
       "direction": "backward",
       "expr": "max by (instance) (max_over_time({filename=~\"$filename\", instance=\"$instance\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]))",
       "legendFormat": "max latency"
      }
     ]
    },
    {
     "title": "HTTP requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 7, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by (status) (count_over_time({filename=~\"$filename\", instance=\"$instance\"} | json |  __error__=\"\" [$__interval]))",
       "legendFormat": "HTTP Status {{status}}"
      }
     ]
    },
    {
     "title": "Bytes Sent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by(status) (sum_over_time({filename=~\"$filename\", instance=\"$instance\"} | json | unwrap body_bytes_sent | __error__=`` [$__interval]))",
       "legendFormat": "Bytes sent: {{status}}"
      }
     ]
    }
   ]
  }
 ]
}