{
 "title": "Uptime Checker | Mirror",
 "description": "Uptime Checker",
 "tags": [ "metrics" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "env", "query": "Mirror" },
   {
    "name": "group",
    "label": "group",
    "query": {
     "query": "label_values(probe_success{env=\"$env\"},group)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(probe_success{env=\"$env\", group=\"$group\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime Overview Last 24h",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{env=\"$env\", group=\"$group\", name!=\"\"}[24h]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Uptime 24h",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(probe_success{env=\"$env\", group=\"$group\", name!=\"\"}[24h])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Uptime 7d",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(probe_success{env=\"$env\", group=\"$group\", name!=\"\"}[7d])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Uptime 30d",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(probe_success{env=\"$env\", group=\"$group\", name!=\"\"}[30d])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Uptime 90d",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(probe_success{env=\"$env\", group=\"$group\", name!=\"\"}[90d])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "probe_success{env=~\"$env\", group=~\"$group\"}"
    },
    {
     "expr": "probe_http_ssl{env=~\"$env\", group=~\"$group\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{env=~\"$env\", group=~\"$group\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_http_status_code{env=~\"$env\", group=~\"$group\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{env=~\"$env\", group=~\"$group\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{env=~\"$env\", group=~\"$group\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{env=~\"$env\", group=~\"$group\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{env=~\"$env\", group=~\"$group\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Probe Phases Duration",
     "type": "timeseries",
     "description": "Duration of http request by phase, summed over all redirects",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "probe_http_duration_seconds{name=~\"$instance\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    }
   ]
  }
 ]
}