{
 "title": "HOME",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Production Alert", "type": "alertlist", "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 } },
  { "title": "Mirror Alert", "type": "alertlist", "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 } },
  { "title": "Staging Alert", "type": "alertlist", "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 } },
  { "title": "Development Alert", "type": "alertlist", "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "Production Uptime 24h",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(group) (avg_over_time(probe_success{name!=\"\", env=\"Production\"}[24h])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mirror Uptime 24h",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(group) (avg_over_time(probe_success{name!=\"\", env=\"Mirror\"}[24h])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Staging Uptime 24h",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(group) (avg_over_time(probe_success{name!=\"\", env=\"Staging\"}[24h])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Development Uptime 24h",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(group) (avg_over_time(probe_success{name!=\"\", env=\"Development\"}[24h])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Production Metrics", "type": "dashlist", "gridPos": { "h": 10, "w": 6, "x": 0, "y": 16 } },
  { "title": "Mirror Metrics", "type": "dashlist", "gridPos": { "h": 10, "w": 6, "x": 6, "y": 16 } },
  { "title": "Staging Metrics", "type": "dashlist", "gridPos": { "h": 10, "w": 6, "x": 12, "y": 16 } },
  { "title": "Development Metrics", "type": "dashlist", "gridPos": { "h": 10, "w": 6, "x": 18, "y": 16 } },
  { "title": "Production Logs", "type": "dashlist", "gridPos": { "h": 10, "w": 6, "x": 0, "y": 26 } },
  { "title": "Mirror Logs", "type": "dashlist", "gridPos": { "h": 10, "w": 6, "x": 6, "y": 26 } },
  { "title": "Staging Logs", "type": "dashlist", "gridPos": { "h": 10, "w": 6, "x": 12, "y": 26 } },
  { "title": "Development Logs", "type": "dashlist", "gridPos": { "h": 10, "w": 6, "x": 18, "y": 26 } }
 ]
}