apiVersion: 1

datasources:
  - name: Mimir
    uid: mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    orgId: 1
    isDefault: true
    editable: true
    basicAuth: true
    basicAuthUser: "${GF_DATASOURCE_USER}"
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "anonymous"
      basicAuthPassword: "${GF_DATASOURCE_PASSWORD}"

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    orgId: 1
    isDefault: false
    editable: true
    basicAuth: true
    basicAuthUser: "${GF_DATASOURCE_USER}"
    secureJsonData:
      basicAuthPassword: "${GF_DATASOURCE_PASSWORD}"

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    orgId: 1
    isDefault: false
    editable: true
    jsonData:
      serviceMap:
        datasourceUid: mimir

      tracesToLogs:
        datasourceUid: loki
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "1m"
        filterByTraceID: true
        filterBySpanID: false

      tracesToMetrics:
        datasourceUid: mimir
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "1m"

      tracesToProfiles:
        datasourceUid: pyroscope

      nodeGraph:
        enabled: true
    secureJsonData:
      basicAuthPassword: "${GF_DATASOURCE_PASSWORD}"
    basicAuth: true
    basicAuthUser: "${GF_DATASOURCE_USER}"

  - name: Pyroscope
    uid: pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://pyroscope:4040
    orgId: 1
    isDefault: false
    editable: true
    basicAuth: true
    basicAuthUser: "${GF_DATASOURCE_USER}"
    jsonData:
      minStep: "15s"
    secureJsonData:
      basicAuthPassword: "${GF_DATASOURCE_PASSWORD}"
